// Effect framework — one-shot effects, continuous effects (7-layer system),
// and replacement effects.
//
// MTG's continuous effect layer system (rule 613):
//   Layer 1: Copy effects
//   Layer 2: Control-changing effects
//   Layer 3: Text-changing effects
//   Layer 4: Type-changing effects
//   Layer 5: Color-changing effects
//   Layer 6: Ability-adding/removing effects
//   Layer 7: Power/toughness effects
//     7a: Characteristic-defining abilities (CDAs)
//     7b: Set P/T to specific values
//     7c: P/T adjustments (+N/+M effects)
//     7d: P/T modifications from counters
//     7e: P/T switching (switch power and toughness)
//
// Ported from mage.abilities.effects.*.

use crate::constants::{Duration, KeywordAbilities, Layer, SubLayer};
use crate::types::{ObjectId, PlayerId};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Continuous effect tracking
// ---------------------------------------------------------------------------

/// A continuous effect currently active in the game.
///
/// These are generated by resolving spells/abilities (e.g. "creatures you
/// control get +1/+1 until end of turn") or from static abilities on
/// permanents. The engine re-applies them each time the game state is
/// recalculated.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ContinuousEffect {
    /// Unique ID for this effect instance.
    pub id: ObjectId,
    /// The source that created this effect.
    pub source_id: ObjectId,
    /// Which player's effects this belongs to (for timestamp ordering).
    pub controller: PlayerId,
    /// How long this effect lasts.
    pub duration: Duration,
    /// Which layer this effect applies in.
    pub layer: Layer,
    /// Sub-layer within layer 7 (only for P/T effects).
    pub sub_layer: Option<SubLayer>,
    /// Timestamp for ordering within the same layer.
    pub timestamp: u64,
    /// The specific modification this effect makes.
    pub modification: EffectModification,
    /// Whether this effect is still active.
    pub active: bool,
}

/// What a continuous effect actually modifies.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum EffectModification {
    /// Layer 1: Copy another object.
    CopyObject {
        target_id: ObjectId,
        copy_of: ObjectId,
    },
    /// Layer 2: Change control of a permanent.
    ChangeControl {
        target_id: ObjectId,
        new_controller: PlayerId,
    },
    /// Layer 4: Add a card type.
    AddType {
        target_id: ObjectId,
        type_name: String,
    },
    /// Layer 4: Remove a card type.
    RemoveType {
        target_id: ObjectId,
        type_name: String,
    },
    /// Layer 5: Change color.
    ChangeColor {
        target_id: ObjectId,
        color: String,
    },
    /// Layer 6: Add a keyword ability.
    AddKeyword {
        target_id: ObjectId,
        keyword: KeywordAbilities,
    },
    /// Layer 6: Remove a keyword ability.
    RemoveKeyword {
        target_id: ObjectId,
        keyword: KeywordAbilities,
    },
    /// Layer 6: Add a keyword to all matching permanents.
    AddKeywordAll {
        filter: String,
        keyword: KeywordAbilities,
        controller: Option<PlayerId>,
    },
    /// Layer 7a: CDA-defined P/T.
    SetBasePowerToughness {
        target_id: ObjectId,
        power: i32,
        toughness: i32,
    },
    /// Layer 7b: Set P/T to specific value (overriding base).
    SetPowerToughness {
        target_id: ObjectId,
        power: i32,
        toughness: i32,
    },
    /// Layer 7c: Modify P/T by amount.
    ModifyPowerToughness {
        target_id: ObjectId,
        power: i32,
        toughness: i32,
    },
    /// Layer 7c: Modify P/T for all matching permanents.
    ModifyPowerToughnessAll {
        filter: String,
        power: i32,
        toughness: i32,
        controller: Option<PlayerId>,
    },
    /// Layer 7e: Switch power and toughness.
    SwitchPowerToughness {
        target_id: ObjectId,
    },
    /// Prevent damage (replacement-like but tracked as continuous).
    PreventDamage {
        target_id: Option<ObjectId>,
        amount: Option<u32>,
    },
    /// Can't attack.
    CantAttack {
        target_id: ObjectId,
    },
    /// Can't block.
    CantBlock {
        target_id: ObjectId,
    },
    /// Custom (for complex effects not captured by the above).
    Custom(String),
}

impl ContinuousEffect {
    /// Create a P/T boost effect (layer 7c) lasting until end of turn.
    pub fn boost_until_eot(
        source_id: ObjectId,
        controller: PlayerId,
        target_id: ObjectId,
        power: i32,
        toughness: i32,
        timestamp: u64,
    ) -> Self {
        ContinuousEffect {
            id: ObjectId::new(),
            source_id,
            controller,
            duration: Duration::EndOfTurn,
            layer: Layer::PTChanging,
            sub_layer: Some(SubLayer::ModifyPT7c),
            timestamp,
            modification: EffectModification::ModifyPowerToughness {
                target_id,
                power,
                toughness,
            },
            active: true,
        }
    }

    /// Create a keyword-granting effect lasting until end of turn.
    pub fn grant_keyword_until_eot(
        source_id: ObjectId,
        controller: PlayerId,
        target_id: ObjectId,
        keyword: KeywordAbilities,
        timestamp: u64,
    ) -> Self {
        ContinuousEffect {
            id: ObjectId::new(),
            source_id,
            controller,
            duration: Duration::EndOfTurn,
            layer: Layer::AbilityAddingRemoving,
            sub_layer: None,
            timestamp,
            modification: EffectModification::AddKeyword {
                target_id,
                keyword,
            },
            active: true,
        }
    }

    /// Create a control-change effect.
    pub fn change_control(
        source_id: ObjectId,
        controller: PlayerId,
        target_id: ObjectId,
        new_controller: PlayerId,
        duration: Duration,
        timestamp: u64,
    ) -> Self {
        ContinuousEffect {
            id: ObjectId::new(),
            source_id,
            controller,
            duration,
            layer: Layer::ControlChanging,
            sub_layer: None,
            timestamp,
            modification: EffectModification::ChangeControl {
                target_id,
                new_controller,
            },
            active: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Continuous effects manager
// ---------------------------------------------------------------------------

/// Manages all active continuous effects in the game.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ContinuousEffects {
    effects: Vec<ContinuousEffect>,
    /// Counter for generating timestamps.
    next_timestamp: u64,
}

impl ContinuousEffects {
    pub fn new() -> Self {
        Self::default()
    }

    /// Get the next timestamp value (monotonically increasing).
    pub fn next_timestamp(&mut self) -> u64 {
        let ts = self.next_timestamp;
        self.next_timestamp += 1;
        ts
    }

    /// Add a new continuous effect.
    pub fn add(&mut self, effect: ContinuousEffect) {
        self.effects.push(effect);
    }

    /// Remove all effects that have expired.
    pub fn remove_expired(&mut self, is_end_of_turn: bool) {
        self.effects.retain(|e| {
            if !e.active {
                return false;
            }
            match e.duration {
                Duration::EndOfTurn => !is_end_of_turn,
                Duration::EndOfCombat => true, // TODO: check combat state
                Duration::WhileOnBattlefield => true, // removed when source leaves
                Duration::Custom => true,
                _ => true,
            }
        });
    }

    /// Remove all effects from a source (when the source leaves the battlefield).
    pub fn remove_from_source(&mut self, source_id: ObjectId) {
        self.effects.retain(|e| e.source_id != source_id);
    }

    /// Get all effects for a specific layer, sorted by timestamp.
    pub fn effects_for_layer(&self, layer: Layer) -> Vec<&ContinuousEffect> {
        let mut effects: Vec<&ContinuousEffect> = self
            .effects
            .iter()
            .filter(|e| e.active && e.layer == layer)
            .collect();
        effects.sort_by_key(|e| e.timestamp);
        effects
    }

    /// Get all effects for a specific layer and sublayer.
    pub fn effects_for_sublayer(&self, layer: Layer, sub_layer: SubLayer) -> Vec<&ContinuousEffect> {
        let mut effects: Vec<&ContinuousEffect> = self
            .effects
            .iter()
            .filter(|e| e.active && e.layer == layer && e.sub_layer == Some(sub_layer))
            .collect();
        effects.sort_by_key(|e| e.timestamp);
        effects
    }

    /// Get all active effects.
    pub fn all(&self) -> &[ContinuousEffect] {
        &self.effects
    }

    /// Total active effects.
    pub fn len(&self) -> usize {
        self.effects.iter().filter(|e| e.active).count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

// ---------------------------------------------------------------------------
// Replacement effect tracking
// ---------------------------------------------------------------------------

/// A replacement effect that modifies an event before it happens.
///
/// Replacement effects follow rule 614: "If [event], [modified event] instead."
/// Examples: "If a creature would die, exile it instead."
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReplacementEffect {
    /// Unique ID.
    pub id: ObjectId,
    /// The source permanent/ability that generates this replacement.
    pub source_id: ObjectId,
    /// The controller of the source.
    pub controller: PlayerId,
    /// Which event type this replaces.
    pub replaces: crate::events::EventType,
    /// Human-readable description.
    pub description: String,
    /// How long this replacement effect lasts.
    pub duration: Duration,
    /// Whether this effect is still active.
    pub active: bool,
    /// The kind of replacement.
    pub replacement: ReplacementKind,
}

/// What kind of replacement to apply.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ReplacementKind {
    /// Prevent the event entirely.
    Prevent,
    /// Exile instead of going to graveyard.
    ExileInstead,
    /// Modify the amount (e.g. double damage, prevent N damage).
    ModifyAmount { delta: i32 },
    /// Redirect to a different target.
    RedirectTarget { new_target: ObjectId },
    /// Enter the battlefield tapped.
    EnterTapped,
    /// Add counters when entering.
    EnterWithCounters { counter_type: String, count: u32 },
    /// Custom replacement.
    Custom(String),
}

/// Stores all active replacement effects.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ReplacementEffects {
    effects: Vec<ReplacementEffect>,
}

impl ReplacementEffects {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a replacement effect.
    pub fn add(&mut self, effect: ReplacementEffect) {
        self.effects.push(effect);
    }

    /// Find all replacement effects that apply to a given event type.
    pub fn for_event(&self, event_type: crate::events::EventType) -> Vec<&ReplacementEffect> {
        self.effects
            .iter()
            .filter(|e| e.active && e.replaces == event_type)
            .collect()
    }

    /// Remove effects from a source.
    pub fn remove_from_source(&mut self, source_id: ObjectId) {
        self.effects.retain(|e| e.source_id != source_id);
    }

    /// Remove expired effects.
    pub fn remove_expired(&mut self, is_end_of_turn: bool) {
        self.effects.retain(|e| {
            if !e.active {
                return false;
            }
            match e.duration {
                Duration::EndOfTurn => !is_end_of_turn,
                _ => true,
            }
        });
    }

    pub fn len(&self) -> usize {
        self.effects.iter().filter(|e| e.active).count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants::{Duration, KeywordAbilities, Layer, SubLayer};

    #[test]
    fn boost_effect() {
        let source = ObjectId::new();
        let target = ObjectId::new();
        let controller = PlayerId::new();

        let effect = ContinuousEffect::boost_until_eot(source, controller, target, 2, 2, 0);

        assert_eq!(effect.layer, Layer::PTChanging);
        assert_eq!(effect.sub_layer, Some(SubLayer::ModifyPT7c));
        assert_eq!(effect.duration, Duration::EndOfTurn);
        assert!(effect.active);

        match &effect.modification {
            EffectModification::ModifyPowerToughness { power, toughness, .. } => {
                assert_eq!(*power, 2);
                assert_eq!(*toughness, 2);
            }
            _ => panic!("wrong modification type"),
        }
    }

    #[test]
    fn keyword_grant_effect() {
        let source = ObjectId::new();
        let target = ObjectId::new();
        let controller = PlayerId::new();

        let effect = ContinuousEffect::grant_keyword_until_eot(
            source,
            controller,
            target,
            KeywordAbilities::FLYING,
            1,
        );

        assert_eq!(effect.layer, Layer::AbilityAddingRemoving);
        assert_eq!(effect.duration, Duration::EndOfTurn);
    }

    #[test]
    fn continuous_effects_manager() {
        let mut mgr = ContinuousEffects::new();
        let source = ObjectId::new();
        let target = ObjectId::new();
        let controller = PlayerId::new();

        let ts = mgr.next_timestamp();
        mgr.add(ContinuousEffect::boost_until_eot(source, controller, target, 1, 1, ts));

        let ts = mgr.next_timestamp();
        mgr.add(ContinuousEffect::grant_keyword_until_eot(
            source, controller, target, KeywordAbilities::TRAMPLE, ts,
        ));

        assert_eq!(mgr.len(), 2);

        let pt_effects = mgr.effects_for_layer(Layer::PTChanging);
        assert_eq!(pt_effects.len(), 1);

        let kw_effects = mgr.effects_for_layer(Layer::AbilityAddingRemoving);
        assert_eq!(kw_effects.len(), 1);

        // End of turn: remove all effects
        mgr.remove_expired(true);
        assert_eq!(mgr.len(), 0);
    }

    #[test]
    fn timestamp_ordering() {
        let mut mgr = ContinuousEffects::new();
        let source = ObjectId::new();
        let target = ObjectId::new();
        let controller = PlayerId::new();

        // Add effects with different timestamps
        let ts1 = mgr.next_timestamp();
        mgr.add(ContinuousEffect::boost_until_eot(source, controller, target, 1, 1, ts1));

        let ts2 = mgr.next_timestamp();
        mgr.add(ContinuousEffect::boost_until_eot(source, controller, target, 2, 2, ts2));

        let effects = mgr.effects_for_layer(Layer::PTChanging);
        assert_eq!(effects.len(), 2);
        // Should be ordered by timestamp
        assert!(effects[0].timestamp < effects[1].timestamp);
    }

    #[test]
    fn remove_from_source() {
        let mut mgr = ContinuousEffects::new();
        let source1 = ObjectId::new();
        let source2 = ObjectId::new();
        let target = ObjectId::new();
        let controller = PlayerId::new();

        mgr.add(ContinuousEffect::boost_until_eot(source1, controller, target, 1, 1, 0));
        mgr.add(ContinuousEffect::boost_until_eot(source2, controller, target, 2, 2, 1));

        assert_eq!(mgr.len(), 2);
        mgr.remove_from_source(source1);
        assert_eq!(mgr.len(), 1);
    }

    #[test]
    fn replacement_effects() {
        let mut replacements = ReplacementEffects::new();

        let source = ObjectId::new();
        let controller = PlayerId::new();

        replacements.add(ReplacementEffect {
            id: ObjectId::new(),
            source_id: source,
            controller,
            replaces: crate::events::EventType::Dies,
            description: "If this creature would die, exile it instead.".to_string(),
            duration: Duration::WhileOnBattlefield,
            active: true,
            replacement: ReplacementKind::ExileInstead,
        });

        let matching = replacements.for_event(crate::events::EventType::Dies);
        assert_eq!(matching.len(), 1);

        let non_matching = replacements.for_event(crate::events::EventType::DamagePlayer);
        assert_eq!(non_matching.len(), 0);
    }
}
